name: wf
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: make setup
      - run: make test
      - run: make lint
