name: wf
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm run build
      - run: npm start
      - run: npm test
      - run: npx eslint .
